// <auto-generated />
namespace PollSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FluentApi2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluentApi2));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041341205_FluentApi2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
